#!/bin/bash

name=$1
clip=$2

echo ":: Operating on $name."; echo

read -p ":: Start of new clip (minutes): " mins
read -p ":: Start of new clip (seconds): " secs
echo ":: Starting clip at $mins:$secs."; echo

read -p ":: End of new clip (minutes): " dmin
read -p ":: End of new clip (seconds): " dsec
echo ":: Clip end will be at $dmin:$dsec."

echo ":: Output file \"$clip\". Beginning..."; echo

mins=$(($mins*60))
startt=$(($mins+$secs))
dmin=$(($dmin*60))
end=$(($dmin+$dsec))
durt=$(($end-$startt))

echo "⇓ FFMPEG OUTPUT ⇓"
ffmpeg -ss $startt -i "$name" -t $durt -codec libopus $clip
echo "-----------------"; echo

echo ":: Complete. Exiting..."
exit
