#!/bin/bash

main() {
    find $HOME/bks -name '.*' -prune -o -print | sed "s|$HOME/bks/||g" | fzf --height=15 | xargs -I {} $READER $HOME/bks/{}
}

invalid() {
    echo "Invalid argument"
    exit 1
}

get() {
    [ -z "$1" ] && invalid
    [ -z "$2" ] && invalid
    wget "$1" -O "$HOME/bks/$2"
}

lst() {
    ls --color=always "$HOME/bks"
}

[ -z "$READER" ] && echo "Please set EDITOR environment variable."

case $1 in
     "get") get "$2" "$3";;
     "ls") lst;;
     "") main;;
     *) invalid;;
esac
