#!/bin/bash

booksdir="$HOME/med/bks"

main() {
    find $booksdir -name '.*' -prune -o -print | sed "s|$booksdir/||g" | fzf --height=15 | xargs -I {} $READER $booksdir/{}
}

invalid() {
    echo "Invalid argument"
    exit 1
}

get() {
    [ -z "$1" ] && invalid
    [ -z "$2" ] && invalid
    wget "$1" -O "$booksdir/$2"
}

lst() {
    ls --color=always "$booksdir"
}

[ -z "$READER" ] && echo "Please set EDITOR environment variable."

case $1 in
    "get") get "$2" "$3";;
    "ls") lst;;
    "") main;;
    *) invalid;;
esac
