#!/bin/bash

musicdir=$(xdg-user-dir MUSIC || echo "$HOME/Music") 

find $musicdir -name '.*' -prune -o -print | sed "s|$musicdir/||g" | fzf --height=15 -m | xargs -r -I {} echo "$musicdir/{}" | xargs -r mpv
