#!/bin/bash

main() {
    find $HOME/scripts -name '.*' -prune -o -print | sed "s|$HOME/scripts/||g" | fzf --height=15 | xargs -I {} $EDITOR $HOME/scripts/{}
}

invalid() {
    echo "Invalid argument"
    exit 1
}

new() {
    [ -z $1 ] && invalid
    path="$HOME/scripts/$1"
    echo -e "#!/bin/bash\n\n<++>" > $path
    chmod +x $path
    $EDITOR $path
}

[ -z $EDITOR ] && echo "Please set EDITOR environment variable." && exit 1

case $1 in
     "new") new "$2";;
     "") main;;
     *) invalid;;
esac
